variables:
   URL: 'https://moodle1click.eummena.org'
   WWW_HOME: '/var/www/moodle-1click'

deploy_to_server:
  stage: deploy
  tags:
    - dev1-shared-runner 
  script:
    - echo "Running deployment scripts"
    - cd packer/files/var/www/moodle-1click/
    - sudo rsync --chown www-data:www-data -avz --delete --exclude ".git/" --filter=":- .gitignore" . $WWW_HOME
    - echo "All done, you may now check $URL"
  only: 
    - dev

stages:
  - deploy
