#!/bin/bash
#
# Scripts in this directory are run during the build process.
# each script will be uploaded to /tmp on your build droplet, 
# given execute permissions and run.  The cleanup process will
# remove the scripts from your build system after they have run
# if you use the build_image task.
#
wget -qO - https://mariadb.org/mariadb_release_signing_key.asc | apt-key add -
add-apt-repository 'deb [arch=amd64] https://ftp.agdsn.de/pub/mirrors/mariadb/repo/10.5/debian buster main'
apt update && apt-get install -y mariadb-server-10.5 mariadb-client-10.5
systemctl enable --now mariadb
