#!/bin/bash

# Download Moodle version 3.9.2 and unpack it over /var/www/moodle
cd /var/www
WWW_HOME="/var/www/moodle"
MOODLEDATA="/var/www/moodledata"
mkdir $WWW_HOME $MOODLEDATA
chown -R www-data:www-data $MOODLEDATA
wget https://github.com/moodle/moodle/archive/v3.9.2.tar.gz && tar xzvf v3.9.2.tar.gz
cd moodle-3.9.2/
rsync --chown www-data:www-data -avz --delete --exclude ".git/" --filter=":- .gitignore" . $WWW_HOME
chown -R www-data:www-data $WWW_HOME
rm -rf /var/www/moodle-3.9.2*/ /var/www/v3.9.2.tar.gz*
cd $WWW_HOME

# Define moodle admin credentials

ADMIN_USER="root"
ADMIN_PASS="Adm1n0plsA$"
echo "$ADMIN_USER:$ADMIN_PASS" > /root/.moodleadmin_password
echo "127.0.0.1 moodle.lms.example" >> /etc/hosts

DB_NAME="moodle"
DB_USER="moodle_user"
DB_PASS="$(cat /root/.moodle_mysql_password|cut -d "=" -f 2|tr -d '\"')"

# Install moodle only in case it isn't already installed
if ! test -f $WWW_HOME/config.php
then
  sudo -u www-data php admin/cli/install.php --lang=en --wwwroot=http://moodle.lms.example --dataroot=$MOODLEDATA --dbname=$DB_NAME --dbuser=$DB_USER --dbpass=$DB_PASS --adminuser=$ADMIN_USER --adminpass=$ADMIN_PASS --fullname="Moodle Learning Management System" --shortname="Moodle" --dbtype=mariadb --non-interactive --allow-unstable --agree-license
fi

# Configure cronjob for moodle under "www-data" user
mkdir /var/log/moodle_cron
touch /var/log/moodle_cron/moodle_cron.log
chown -R www-data:www-data /var/log/moodle_cron
echo "* * * * * /usr/bin/php $WWW_HOME/admin/cli/cron.php >> /var/log/moodle_cron/moodle_cron.log 2>&1" >> /var/spool/cron/crontabs/www-data
