#!/bin/bash
#
# Scripts in this directory are run during the build process.
# each script will be uploaded to /tmp on your build droplet, 
# given execute permissions and run.  The cleanup process will
# remove the scripts from your build system after they have run
# if you use the build_image task.
#
ufw enable
ufw allow in on eth0 to any port 443 proto tcp
ufw allow in on eth0 to any port 80 proto tcp
ufw allow in on eth0 to any port 22 proto tcp
