#!/bin/sh
#
# Configured as part of the DigitalOcean 1-Click Image build process

myip=$(hostname -I | awk '{print$1}')
cat <<EOF
********************************************************************************

Welcome to the One-Click Moodle LMS Droplet.
To keep this Droplet secure, the UFW firewall is enabled.
All ports are BLOCKED except 22 (SSH), 80 (HTTP), and 443 (HTTPS).

On your local linux machine put the following line inside the /etc/hosts file:

"$myip moodle.lms.example"

In a web browser, you can view:
 * The Moodle LMS website by visiting the following URL: http://moodle.lms.example

On the server:
 * The randomized mysql root password is saved in /root/.root_mysql_password
 * The randomized moodle mysql password is saved in /root/.moodle_mysql_password
 * The Moodle LMS web root is located at /var/www/moodle
 * The moodledata are located in /var/www/moodledata
 * The Moodle LMS admin password is saved in /root/.moodleadmin_password
 * Certbot is preinstalled. Run it to configure HTTPS, after successfully registering a new domain name for the IP of the Droplet

********************************************************************************
To delete this message of the day: rm -rf $(readlink -f ${0})
EOF
